version: "2"
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.3
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_PASSWORD=moodle
      - MARIADB_ROOT_PASSWORD=moodle
    volumes:
      - "mariadb_data:/bitnami/mariadb"
  moodle:
    image: docker.io/bitnami/moodle:4.3
    ports:
      - "8080:8080"
      - "443:8443"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_USERNAME=ballerinevolanti
      - MOODLE_PASSWORD=ballerinevolanti
    volumes:
      - "moodle_data:/bitnami/moodle"
      - "moodledata_data:/bitnami/moodledata"
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
